export const ERROR_CODES = {
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASKS_NOT_FOUND: 'TASKS_NOT_FOUND',
  USERS_NOT_FOUND: 'USERS_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INCORRECT_DATA: 'INCORRECT_DATA',
  FILE_NOT_PROVIDED: 'FILE_NOT_PROVIDED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
};
